version: 0.2

datasource:
  endpoint: ${endpoint}
  accesskey: ${accesskey}
  secretkey: ${secretkey}
  region: ${region}
phases:
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean package
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/TripnaryServer.jar
  discard-paths: yes

