package com.example.tripnaryserver.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@DynamoDBTable(tableName = "dias_viajes")
public class Dia_ViajeDef {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id_dia;

    @DynamoDBAttribute
    private Date fecha_dia;

    @DynamoDBAttribute
    private String comentarios;

    @DynamoDBAttribute
    private String id_viaje;

    @DynamoDBAttribute
    private String estado;
}
