package com.example.tripnaryserver.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.sql.Date;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@DynamoDBTable(tableName = "viajes")
public class ViajeDef {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String idViaje;

    @DynamoDBAttribute
    private String descripcion;

    @DynamoDBAttribute
    private String fechaInicio;

    @DynamoDBAttribute
    private String fechaFin;

    @DynamoDBAttribute
    private String destino;

    @DynamoDBAttribute
    private String idUsuario;

    @DynamoDBAttribute
    private String estado;

}
